# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nipa_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nipa_service.proto',
  package='nipa_demo',
  syntax='proto3',
  serialized_options=b'\n\025com.ketiair.nipa_demoB\010NipaDemoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12nipa_service.proto\x12\tnipa_demo\"^\n\nImgRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x13\n\x0borientation\x18\x02 \x01(\x05\x12\r\n\x05\x66rame\x18\x03 \x01(\x0c\x12\x0c\n\x04time\x18\x04 \x01(\x02\x12\x11\n\tframe_num\x18\x05 \x01(\x05\"7\n\x0b\x43hatRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05\x61udio\x18\x03 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x0c\"\x13\n\x04User\x12\x0b\n\x03uid\x18\x01 \x01(\t\"\x1e\n\x0c\x44ummyRequest\x12\x0e\n\x06result\x18\x01 \x01(\t2\xbd\x02\n\x10StreamingService\x12\x42\n\x0eImageStreaming\x12\x15.nipa_demo.ImgRequest\x1a\x13.nipa_demo.Response\"\x00(\x01\x30\x01\x12\x35\n\x04\x43hat\x12\x16.nipa_demo.ChatRequest\x1a\x13.nipa_demo.Response\"\x00\x12=\n\x0bGetUserList\x12\x17.nipa_demo.DummyRequest\x1a\x13.nipa_demo.Response\"\x00\x12\x35\n\x0bGetUserData\x12\x0f.nipa_demo.User\x1a\x13.nipa_demo.Response\"\x00\x12\x38\n\x0eGetUserHistory\x12\x0f.nipa_demo.User\x1a\x13.nipa_demo.Response\"\x00\x42#\n\x15\x63om.ketiair.nipa_demoB\x08NipaDemoP\x01\x62\x06proto3'
)




_IMGREQUEST = _descriptor.Descriptor(
  name='ImgRequest',
  full_name='nipa_demo.ImgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='nipa_demo.ImgRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='nipa_demo.ImgRequest.orientation', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame', full_name='nipa_demo.ImgRequest.frame', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='nipa_demo.ImgRequest.time', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_num', full_name='nipa_demo.ImgRequest.frame_num', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=127,
)


_CHATREQUEST = _descriptor.Descriptor(
  name='ChatRequest',
  full_name='nipa_demo.ChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='nipa_demo.ChatRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='nipa_demo.ChatRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio', full_name='nipa_demo.ChatRequest.audio', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=184,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='nipa_demo.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='nipa_demo.Response.result', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=212,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='nipa_demo.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='nipa_demo.User.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=233,
)


_DUMMYREQUEST = _descriptor.Descriptor(
  name='DummyRequest',
  full_name='nipa_demo.DummyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='nipa_demo.DummyRequest.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=265,
)

DESCRIPTOR.message_types_by_name['ImgRequest'] = _IMGREQUEST
DESCRIPTOR.message_types_by_name['ChatRequest'] = _CHATREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['DummyRequest'] = _DUMMYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImgRequest = _reflection.GeneratedProtocolMessageType('ImgRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMGREQUEST,
  '__module__' : 'nipa_service_pb2'
  # @@protoc_insertion_point(class_scope:nipa_demo.ImgRequest)
  })
_sym_db.RegisterMessage(ImgRequest)

ChatRequest = _reflection.GeneratedProtocolMessageType('ChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATREQUEST,
  '__module__' : 'nipa_service_pb2'
  # @@protoc_insertion_point(class_scope:nipa_demo.ChatRequest)
  })
_sym_db.RegisterMessage(ChatRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'nipa_service_pb2'
  # @@protoc_insertion_point(class_scope:nipa_demo.Response)
  })
_sym_db.RegisterMessage(Response)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'nipa_service_pb2'
  # @@protoc_insertion_point(class_scope:nipa_demo.User)
  })
_sym_db.RegisterMessage(User)

DummyRequest = _reflection.GeneratedProtocolMessageType('DummyRequest', (_message.Message,), {
  'DESCRIPTOR' : _DUMMYREQUEST,
  '__module__' : 'nipa_service_pb2'
  # @@protoc_insertion_point(class_scope:nipa_demo.DummyRequest)
  })
_sym_db.RegisterMessage(DummyRequest)


DESCRIPTOR._options = None

_STREAMINGSERVICE = _descriptor.ServiceDescriptor(
  name='StreamingService',
  full_name='nipa_demo.StreamingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=268,
  serialized_end=585,
  methods=[
  _descriptor.MethodDescriptor(
    name='ImageStreaming',
    full_name='nipa_demo.StreamingService.ImageStreaming',
    index=0,
    containing_service=None,
    input_type=_IMGREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Chat',
    full_name='nipa_demo.StreamingService.Chat',
    index=1,
    containing_service=None,
    input_type=_CHATREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserList',
    full_name='nipa_demo.StreamingService.GetUserList',
    index=2,
    containing_service=None,
    input_type=_DUMMYREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserData',
    full_name='nipa_demo.StreamingService.GetUserData',
    index=3,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserHistory',
    full_name='nipa_demo.StreamingService.GetUserHistory',
    index=4,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMINGSERVICE)

DESCRIPTOR.services_by_name['StreamingService'] = _STREAMINGSERVICE

# @@protoc_insertion_point(module_scope)
