# Copyright 2021 san kim
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -t nipa_demo/voice_chat .

# docker tag nipa_demo/voice_chat 10.0.0.161:5000/voice_chat
# docker push 10.0.0.161:5000/voice_chat

# docker run --gpus all --rm -d -it -p 20443:20443 --name voice_chat nipa_demo/voice_chat
# or if you use nvidia-docker
# nvidia-docker run --rm -d -it -p 20443:20443 --name voice_chat nipa_demo/voice_chat

# docker -H 10.0.0.110:2375 run --gpus all --rm -d -it --network="dockernet" --ip="10.1.92.126" --name voice_chat 10.0.0.161:5000/voice_chat

FROM node:slim

ENV DEBIAN_FRONTEND noninteractive
ENV SERVICE_PORT 20443

ENV ketiPort 28443
ENV ketiHost ketiair.com

ADD app /root/app

WORKDIR /root/app

RUN npm i

CMD ["npm", "start"]

EXPOSE ${SERVICE_PORT}

